<?php
// EventCommitments model metadata for Gravitycar framework
return [
    'name' => 'EventCommitments',
    'table' => 'event_commitments',
    'displayColumns' => ['event_display', 'user_display', 'is_available'],
    'fields' => [
        'event_id' => [
            'name' => 'event_id',
            'type' => 'RelatedRecord',
            'label' => 'Event',
            'required' => true,
            'relatedModel' => 'Events',
            'relatedFieldName' => 'id',
            'displayFieldName' => 'event_display',
            'description' => 'The event this commitment belongs to',
            'validationRules' => ['Required'],
        ],
        'event_display' => [
            'name' => 'event_display',
            'type' => 'Text',
            'label' => 'Event Name',
            'readOnly' => true,
            'isDBField' => false,
            'description' => 'Display name of the event',
            'validationRules' => [],
        ],
        'user_id' => [
            'name' => 'user_id',
            'type' => 'RelatedRecord',
            'label' => 'User',
            'required' => true,
            'relatedModel' => 'Users',
            'relatedFieldName' => 'id',
            'displayFieldName' => 'user_display',
            'description' => 'The invited user making this commitment',
            'validationRules' => ['Required'],
        ],
        'user_display' => [
            'name' => 'user_display',
            'type' => 'Text',
            'label' => 'User',
            'readOnly' => true,
            'isDBField' => false,
            'description' => 'Display name of the user',
            'validationRules' => [],
        ],
        'proposed_date_id' => [
            'name' => 'proposed_date_id',
            'type' => 'RelatedRecord',
            'label' => 'Proposed Date',
            'required' => true,
            'relatedModel' => 'EventProposedDates',
            'relatedFieldName' => 'id',
            'displayFieldName' => 'proposed_date_display',
            'description' => 'The proposed date this commitment is for',
            'validationRules' => ['Required'],
        ],
        'proposed_date_display' => [
            'name' => 'proposed_date_display',
            'type' => 'Text',
            'label' => 'Proposed Date',
            'readOnly' => true,
            'isDBField' => false,
            'description' => 'Display value of the proposed date',
            'validationRules' => [],
        ],
        'is_available' => [
            'name' => 'is_available',
            'type' => 'Boolean',
            'label' => 'Available',
            'required' => true,
            'defaultValue' => false,
            'description' => 'Whether the user can attend on this date',
            'validationRules' => ['Required'],
        ],
    ],
    'rolesAndActions' => [
        'admin' => ['*'],
        'user' => [],
        'guest' => [],
    ],
    'validationRules' => [],
    'relationships' => [],
    'apiRoutes' => [],
    'uniqueConstraints' => [
        'uniq_event_user_date' => ['event_id', 'user_id', 'proposed_date_id'],
    ],
    'ui' => [
        'listFields' => ['event_display', 'user_display', 'proposed_date_display', 'is_available'],
        'createFields' => ['event_id', 'user_id', 'proposed_date_id', 'is_available'],
        'editFields' => ['is_available'],
    ],
];
