<?php
// Users model metadata for Gravitycar framework
return [
    'name' => 'Users',
    'table' => 'users',
    'fields' => [
        'id' => [
            'name' => 'id',
            'type' => 'ID',
            'label' => 'User ID',
            'required' => true,
            'readOnly' => true,
            'unique' => true,
        ],
        'username' => [
            'name' => 'username',
            'type' => 'Text',
            'label' => 'Username',
            'required' => false, // Made optional for OAuth users
            'unique' => true,
            'validationRules' => ['Unique'],
        ],
        'password' => [
            'name' => 'password',
            'type' => 'Password',
            'label' => 'Password',
            'required' => false, // Made optional for OAuth users
            'validationRules' => [],
        ],
        'email' => [
            'name' => 'email',
            'type' => 'Email',
            'label' => 'Email',
            'required' => true,
            'unique' => true,
            'validationRules' => ['Email', 'Required', 'Unique'],
        ],
        'first_name' => [
            'name' => 'first_name',
            'type' => 'Text',
            'label' => 'First Name',
            'required' => false,
            'validationRules' => ['Alphanumeric'],
        ],
        'last_name' => [
            'name' => 'last_name',
            'type' => 'Text',
            'label' => 'Last Name',
            'required' => true,
            'validationRules' => ['Alphanumeric', 'Required'],
        ],
        'google_id' => [
            'name' => 'google_id',
            'type' => 'Text',
            'label' => 'Google ID',
            'required' => false,
            'unique' => true,
            'validationRules' => ['Unique'],
        ],
        'auth_provider' => [
            'name' => 'auth_provider',
            'type' => 'Enum',
            'label' => 'Authentication Provider',
            'required' => true,
            'defaultValue' => 'local',
            'options' => [
                'local' => 'Local Authentication',
                'google' => 'Google OAuth',
                'hybrid' => 'Both Local and Google',
            ],
            'validationRules' => ['Required', 'Options'],
        ],
        'last_login_method' => [
            'name' => 'last_login_method',
            'type' => 'Enum',
            'label' => 'Last Login Method',
            'required' => false,
            'options' => [
                'local' => 'Username/Password',
                'google' => 'Google OAuth',
            ],
            'validationRules' => ['Options'],
        ],
        'email_verified_at' => [
            'name' => 'email_verified_at',
            'type' => 'DateTime',
            'label' => 'Email Verified At',
            'required' => false,
            'readOnly' => true,
            'validationRules' => ['DateTime'],
        ],
        'profile_picture_url' => [
            'name' => 'profile_picture_url',
            'type' => 'Image',
            'label' => 'Profile Picture URL',
            'required' => false,
            'width' => 150,
            'height' => 150,
            'validationRules' => ['URL'],
        ],
        'last_google_sync' => [
            'name' => 'last_google_sync',
            'type' => 'DateTime',
            'label' => 'Last Google Profile Sync',
            'required' => false,
            'readOnly' => true,
            'validationRules' => ['DateTime'],
        ],
        'is_active' => [
            'name' => 'is_active',
            'type' => 'Boolean',
            'label' => 'Active Status',
            'required' => true,
            'defaultValue' => true,
            'validationRules' => ['Required'],
        ],
        'last_login' => [
            'name' => 'last_login',
            'type' => 'DateTime',
            'label' => 'Last Login',
            'required' => false,
            'readOnly' => true,
            'validationRules' => ['DateTime'],
        ],
        'user_type' => [
            'name' => 'user_type',
            'type' => 'Enum',
            'label' => 'User Type',
            'required' => true,
            'defaultValue' => 'user',
            'options' => [
                'admin' => 'Admin',
                'manager' => 'Manager',
                'user' => 'User',
            ],
            'validationRules' => ['Required', 'Options'],
        ],
        'user_timezone' => [
            'name' => 'user_timezone',
            'type' => 'Enum',
            'label' => 'Timezone',
            'required' => true,
            'defaultValue' => 'UTC',
            'optionsClass' => '\Gravitycar\Utils\Timezone',
            'optionsMethod' => 'getTimezones',
            'validationRules' => ['Required', 'Options'],
        ],
        // Core fields
        'created_at' => [
            'name' => 'created_at',
            'type' => 'DateTime',
            'label' => 'Created At',
            'readOnly' => true,
        ],
        'updated_at' => [
            'name' => 'updated_at',
            'type' => 'DateTime',
            'label' => 'Updated At',
            'readOnly' => true,
        ],
        'deleted_at' => [
            'name' => 'deleted_at',
            'type' => 'DateTime',
            'label' => 'Deleted At',
            'readOnly' => true,
        ],
        'created_by' => [
            'name' => 'created_by',
            'type' => 'ID',
            'label' => 'Created By',
            'readOnly' => true,
        ],
        'updated_by' => [
            'name' => 'updated_by',
            'type' => 'ID',
            'label' => 'Updated By',
            'readOnly' => true,
        ],
        'deleted_by' => [
            'name' => 'deleted_by',
            'type' => 'ID',
            'label' => 'Deleted By',
            'readOnly' => true,
        ],
    ],
    'validationRules' => [],
    'relationships' => [
        'roles' => [
            'type' => 'ManyToMany',
            'model' => 'Roles',
            'through' => 'user_roles',
            'foreignKey' => 'user_id',
            'otherKey' => 'role_id',
        ],
        'permissions' => [
            'type' => 'ManyToMany',
            'model' => 'Permissions',
            'through' => 'user_permissions',
            'foreignKey' => 'user_id',
            'otherKey' => 'permission_id',
        ],
        'jwt_refresh_tokens' => [
            'type' => 'HasMany',
            'model' => 'JwtRefreshTokens',
            'foreignKey' => 'user_id',
            'localKey' => 'id',
        ],
        'google_oauth_tokens' => [
            'type' => 'HasMany',
            'model' => 'GoogleOauthTokens',
            'foreignKey' => 'user_id',
            'localKey' => 'id',
        ],
    ],
    'ui' => [
        'listFields' => ['username', 'email', 'auth_provider', 'user_type', 'is_active', 'last_login'],
        'createFields' => ['username', 'password', 'email', 'first_name', 'last_name', 'user_type', 'user_timezone', 'is_active'],
    ],
];
