<?php
// EmailQueue model metadata for Gravitycar framework
return [
    'name' => 'EmailQueue',
    'table' => 'email_queue',
    'displayColumns' => ['recipient_email', 'subject', 'status'],
    'fields' => [
        'recipient_email' => [
            'name' => 'recipient_email',
            'type' => 'Text',
            'label' => 'Recipient Email',
            'required' => true,
            'validationRules' => ['Required', 'Email'],
        ],
        'recipient_user_id' => [
            'name' => 'recipient_user_id',
            'type' => 'RelatedRecord',
            'label' => 'Recipient User',
            'required' => false,
            'relatedModel' => 'Users',
            'validationRules' => [],
        ],
        'subject' => [
            'name' => 'subject',
            'type' => 'Text',
            'label' => 'Subject',
            'required' => true,
            'validationRules' => ['Required'],
        ],
        'body' => [
            'name' => 'body',
            'type' => 'BigText',
            'label' => 'Body',
            'required' => true,
            'validationRules' => ['Required'],
        ],
        'status' => [
            'name' => 'status',
            'type' => 'Enum',
            'label' => 'Status',
            'required' => true,
            'defaultValue' => 'pending',
            'options' => [
                'pending' => 'Pending',
                'sent' => 'Sent',
                'failed' => 'Failed',
                'cancelled' => 'Cancelled',
            ],
            'validationRules' => ['Required', 'Options'],
        ],
        'send_at' => [
            'name' => 'send_at',
            'type' => 'DateTime',
            'label' => 'Scheduled Send Time',
            'required' => true,
            'validationRules' => ['Required', 'DateTime'],
        ],
        'sent_at' => [
            'name' => 'sent_at',
            'type' => 'DateTime',
            'label' => 'Sent At',
            'required' => false,
            'readOnly' => true,
            'validationRules' => ['DateTime'],
        ],
        'retry_count' => [
            'name' => 'retry_count',
            'type' => 'Integer',
            'label' => 'Retry Count',
            'required' => false,
            'defaultValue' => 0,
            'validationRules' => [],
        ],
        'error_message' => [
            'name' => 'error_message',
            'type' => 'Text',
            'label' => 'Error Message',
            'required' => false,
            'validationRules' => [],
        ],
        'related_event_id' => [
            'name' => 'related_event_id',
            'type' => 'RelatedRecord',
            'label' => 'Related Event',
            'required' => false,
            'relatedModel' => 'Events',
            'validationRules' => [],
        ],
        'related_reminder_id' => [
            'name' => 'related_reminder_id',
            'type' => 'RelatedRecord',
            'label' => 'Related Reminder',
            'required' => false,
            'relatedModel' => 'EventReminders',
            'validationRules' => [],
        ],
        // End of model-specific fields
    ],

    'rolesAndActions' => [
        'admin' => ['*'],
        'user' => [],
        'guest' => [],
    ],

    'validationRules' => [],
    'relationships' => [],
    'apiRoutes' => [],
    'ui' => [
        'listFields' => [
            'recipient_email',
            'subject',
            'status',
            'send_at',
            'sent_at',
            'retry_count',
        ],
        'createFields' => [
            'recipient_email',
            'recipient_user_id',
            'subject',
            'body',
            'status',
            'send_at',
            'related_event_id',
            'related_reminder_id',
        ],
        'editFields' => [
            'recipient_email',
            'recipient_user_id',
            'subject',
            'body',
            'status',
            'send_at',
            'sent_at',
            'retry_count',
            'error_message',
            'related_event_id',
            'related_reminder_id',
        ],
    ],
];
