<?php
// Movie_Quote_Trivia_Questions model metadata for Gravitycar framework
return [
    'name' => 'Movie_Quote_Trivia_Questions',
    'table' => 'movie_quote_trivia_questions',
    'displayColumns' => ['movie_quote_display', 'answered_correctly'],
    'fields' => [
        'movie_quote_id' => [
            'name' => 'movie_quote_id',
            'type' => 'RelatedRecord',
            'label' => 'Movie Quote',
            'required' => true,
            'relatedModel' => 'Movie_Quotes',
            'relatedFieldName' => 'id',
            'displayFieldName' => 'movie_quote_display',
            'description' => 'The movie quote this trivia question is based on',
            'validationRules' => ['Required'],
        ],
        'movie_quote_display' => [
            'name' => 'movie_quote_display',
            'type' => 'Text',
            'label' => 'Movie Quote Text',
            'readOnly' => true,
            'isDBField' => false,
            'description' => 'Display text for the movie quote',
            'validationRules' => [],
        ],
        'answers' => [
            'name' => 'answers',
            'type' => 'RadioButtonSet',
            'label' => 'Answer Options',
            'required' => false,
            'nullable' => true,
            'layout' => 'vertical',
            'allowClear' => false,
            'optionsClass' => 'Gravitycar\\Models\\movie_quote_trivia_questions\\Movie_Quote_Trivia_Questions',
            'optionsMethod' => 'getAnswerOptionsForField',
            'description' => 'Three movie title options - select the correct one',
            'validationRules' => [],
        ],
        'correct_answer' => [
            'name' => 'correct_answer',
            'type' => 'ID',
            'label' => 'Correct Answer',
            'readOnly' => true,
            'isDBField' => true,
            'required' => true,
            'description' => 'ID of the correct movie (hidden from UI)',
            'validationRules' => ['Required'],
        ],
        'answer_option_1' => [
            'name' => 'answer_option_1',
            'type' => 'ID',
            'label' => 'Answer Option 1',
            'readOnly' => true,
            'isDBField' => true,
            'required' => true,
            'description' => 'First movie option (hidden from UI)',
            'validationRules' => ['Required'],
        ],
        'answer_option_2' => [
            'name' => 'answer_option_2',
            'type' => 'ID',
            'label' => 'Answer Option 2',
            'readOnly' => true,
            'isDBField' => true,
            'required' => true,
            'description' => 'Second movie option (hidden from UI)',
            'validationRules' => ['Required'],
        ],
        'answer_option_3' => [
            'name' => 'answer_option_3',
            'type' => 'ID',
            'label' => 'Answer Option 3',
            'readOnly' => true,
            'isDBField' => true,
            'required' => true,
            'description' => 'Third movie option (hidden from UI)',
            'validationRules' => ['Required'],
        ],
        'answered_correctly' => [
            'name' => 'answered_correctly',
            'type' => 'Boolean',
            'label' => 'Answered Correctly',
            'required' => false,
            'defaultValue' => false,
            'description' => 'Whether this question was answered correctly',
            'validationRules' => [],
        ],
        'obscurity_score' => [
            'name' => 'obscurity_score',
            'type' => 'Integer',
            'label' => 'Obscurity Score',
            'minValue' => 1,
            'maxValue' => 5,
            'readOnly' => true,
            'nullable' => true,
            'description' => 'Film obscurity: 1=Very Popular, 5=Very Obscure',
        ],
        // End of model-specific fields
    ],
    'validationRules' => [],
    'relationships' => [],
    'ui' => [
        'listFields' => ['movie_quote_display', 'answered_correctly', 'obscurity_score'],
        'createFields' => ['movie_quote_id', 'answers'],
        'editFields' => ['movie_quote_id', 'answers', 'answered_correctly'],
        // Note: Fields not listed in createFields/editFields/listFields are automatically hidden
        // The frontend uses positive inclusion rather than negative exclusion
    ],
];
