<?php
// Movie_Quote_Trivia_Questions model metadata for Gravitycar framework
return [
    'name' => 'Movie_Quote_Trivia_Questions',
    'table' => 'movie_quote_trivia_questions',
    'displayColumns' => ['movie_quote_display', 'answered_correctly'],
    'fields' => [
        'movie_quote_id' => [
            'name' => 'movie_quote_id',
            'type' => 'RelatedRecord',
            'label' => 'Movie Quote',
            'required' => true,
            'relatedModel' => 'Movie_Quotes',
            'relatedFieldName' => 'id',
            'displayFieldName' => 'movie_quote_display',
            'description' => 'The movie quote this trivia question is based on',
            'validationRules' => ['Required'],
        ],
        'movie_quote_display' => [
            'name' => 'movie_quote_display',
            'type' => 'Text',
            'label' => 'Movie Quote Text',
            'readOnly' => true,
            'isDBField' => false,
            'description' => 'Display text for the movie quote',
            'validationRules' => [],
        ],
        'answers' => [
            'name' => 'answers',
            'type' => 'RadioButtonSet',
            'label' => 'Answer Options',
            'required' => false,
            'nullable' => true,
            'layout' => 'vertical',
            'allowClear' => false,
            'optionsClass' => 'Gravitycar\\Models\\movie_quote_trivia_questions\\Movie_Quote_Trivia_Questions',
            'optionsMethod' => 'getAnswerOptionsForField',
            'description' => 'Three movie title options - select the correct one',
            'validationRules' => [],
        ],
        'correct_answer' => [
            'name' => 'correct_answer',
            'type' => 'ID',
            'label' => 'Correct Answer',
            'readOnly' => true,
            'isDBField' => true,
            'required' => true,
            'description' => 'ID of the correct movie (hidden from UI)',
            'validationRules' => ['Required'],
        ],
        'answer_option_1' => [
            'name' => 'answer_option_1',
            'type' => 'ID',
            'label' => 'Answer Option 1',
            'readOnly' => true,
            'isDBField' => true,
            'required' => true,
            'description' => 'First movie option (hidden from UI)',
            'validationRules' => ['Required'],
        ],
        'answer_option_2' => [
            'name' => 'answer_option_2',
            'type' => 'ID',
            'label' => 'Answer Option 2',
            'readOnly' => true,
            'isDBField' => true,
            'required' => true,
            'description' => 'Second movie option (hidden from UI)',
            'validationRules' => ['Required'],
        ],
        'answer_option_3' => [
            'name' => 'answer_option_3',
            'type' => 'ID',
            'label' => 'Answer Option 3',
            'readOnly' => true,
            'isDBField' => true,
            'required' => true,
            'description' => 'Third movie option (hidden from UI)',
            'validationRules' => ['Required'],
        ],
        'answered_correctly' => [
            'name' => 'answered_correctly',
            'type' => 'Boolean',
            'label' => 'Answered Correctly',
            'required' => false,
            'defaultValue' => false,
            'description' => 'Whether this question was answered correctly',
            'validationRules' => [],
        ],
        'obscurity_score' => [
            'name' => 'obscurity_score',
            'type' => 'Integer',
            'label' => 'Obscurity Score',
            'minValue' => 1,
            'maxValue' => 5,
            'readOnly' => true,
            'nullable' => true,
            'description' => 'Film obscurity: 1=Very Popular, 5=Very Obscure',
            'validationRules' => [],
        ],
        
        // NEW GAME SESSION FIELDS (added for trivia game support)
        'game_id' => [
            'name' => 'game_id',
            'type' => 'UUID',
            'label' => 'Game Session',
            'required' => false, // Allow standalone questions and game-linked questions
            'nullable' => true,
            'readOnly' => true,
            'description' => 'Links question to specific game session (null for standalone questions)',
            'validationRules' => [],
        ],
        'question_order' => [
            'name' => 'question_order',
            'type' => 'Integer',
            'label' => 'Question Order',
            'required' => false,
            'minValue' => 1,
            'maxValue' => 15,
            'nullable' => true,
            'readOnly' => true,
            'description' => 'Question sequence within game (1-15, null for standalone)',
            'validationRules' => [],
        ],
        'user_selected_option' => [
            'name' => 'user_selected_option',
            'type' => 'Integer',
            'label' => 'User Selected Option',
            'required' => false,
            'minValue' => 1,
            'maxValue' => 3,
            'nullable' => true,
            'description' => 'Which option player selected (1, 2, or 3)',
            'validationRules' => [],
        ],
        'answered_at' => [
            'name' => 'answered_at',
            'type' => 'DateTime',
            'label' => 'Answered At',
            'required' => false,
            'nullable' => true,
            'description' => 'Timestamp when question was answered',
            'validationRules' => ['DateTime'],
        ],
        'time_taken_seconds' => [
            'name' => 'time_taken_seconds',
            'type' => 'Integer',
            'label' => 'Time Taken (Seconds)',
            'required' => false,
            'minValue' => 0,
            'nullable' => true,
            'description' => 'Seconds taken to answer question (for scoring)',
            'validationRules' => [],
        ],
        // End of model-specific fields
    ],
    'validationRules' => [],
    'relationships' => [],
    'ui' => [
        'listFields' => [
            'movie_quote_display', 
            'answered_correctly', 
            'obscurity_score',
            'question_order',           // NEW
            'user_selected_option',     // NEW
            'time_taken_seconds'        // NEW
        ],
        'createFields' => ['movie_quote_id', 'answers'], // Keep existing - standalone questions
        'editFields' => [
            'movie_quote_id', 
            'answers', 
            'answered_correctly',
            'user_selected_option'      // NEW - allow updating answer selection
        ],
        // Note: Fields not listed in createFields/editFields/listFields are automatically hidden
        // The frontend uses positive inclusion rather than negative exclusion
    ],
    'rolesAndActions' => [
        'admin' => ['*'], // Only admins can manage permissions
        'manager' => ['read', 'create', 'update', 'delete'],
        'user' => ['read', 'create', 'update', 'delete'],
        'guest' => ['read', 'create', 'update', 'delete'],
    ],
];
