<?php
// Events model metadata for Gravitycar framework
return [
    'name' => 'Events',
    'table' => 'events',
    'displayColumns' => ['name'],
    'fields' => [
        'name' => [
            'name' => 'name',
            'type' => 'Text',
            'label' => 'Event Name',
            'required' => true,
            'validationRules' => ['Required'],
        ],
        'description' => [
            'name' => 'description',
            'type' => 'Text',
            'label' => 'Description',
            'required' => false,
            'validationRules' => [],
        ],
        'location' => [
            'name' => 'location',
            'type' => 'Text',
            'label' => 'Location',
            'required' => false,
            'validationRules' => [],
        ],
        'duration_hours' => [
            'name' => 'duration_hours',
            'type' => 'Integer',
            'label' => 'Duration (Hours)',
            'required' => false,
            'defaultValue' => 3,
            'validationRules' => [],
        ],
        'accepted_date' => [
            'name' => 'accepted_date',
            'type' => 'DateTime',
            'label' => 'Accepted Date',
            'required' => false,
            'validationRules' => ['DateTime'],
        ],
        'linked_model_name' => [
            'name' => 'linked_model_name',
            'type' => 'Text',
            'label' => 'Linked Model',
            'required' => false,
            'validationRules' => [],
        ],
        'linked_record_id' => [
            'name' => 'linked_record_id',
            'type' => 'ID',
            'label' => 'Linked Record ID',
            'required' => false,
            'validationRules' => [],
        ],
    ],
    'rolesAndActions' => [
        'admin' => ['*'],
        'user' => ['list', 'read'],
        'guest' => ['list', 'read'],
    ],
    'validationRules' => [],
    'relationships' => [
        'events_event_proposed_dates',
        'events_users_invitations',
        'events_event_commitments',
        'events_event_reminders',
    ],
    'apiRoutes' => [],
    'ui' => [
        'listFields' => ['name', 'location', 'accepted_date', 'duration_hours'],
        'createFields' => ['name', 'description', 'location', 'duration_hours', 'linked_model_name', 'linked_record_id'],
        'editFields' => ['name', 'description', 'location', 'duration_hours', 'accepted_date', 'linked_model_name', 'linked_record_id'],
        'relatedItemsSections' => [
            'proposed_dates' => [
                'title' => 'Proposed Dates',
                'relationship' => 'events_event_proposed_dates',
                'mode' => 'children_management',
                'relatedModel' => 'EventProposedDates',
                'displayColumns' => ['proposed_date'],
                'actions' => ['create', 'delete'],
                'allowInlineCreate' => true,
                'allowInlineEdit' => false,
                'createFields' => ['proposed_date'],
                'editFields' => [],
            ],
            'invitations' => [
                'title' => 'Invited Users',
                'relationship' => 'events_users_invitations',
                'mode' => 'children_management',
                'relatedModel' => 'Users',
                'displayColumns' => ['first_name', 'last_name', 'email'],
                'actions' => ['create', 'delete'],
                'allowInlineCreate' => true,
                'allowInlineEdit' => false,
                'createFields' => ['user_id'],
                'editFields' => [],
            ],
            'reminders' => [
                'title' => 'Reminders',
                'relationship' => 'events_event_reminders',
                'mode' => 'children_management',
                'relatedModel' => 'EventReminders',
                'displayColumns' => ['reminder_type', 'remind_at', 'status'],
                'actions' => ['create', 'delete'],
                'allowInlineCreate' => true,
                'allowInlineEdit' => false,
                'createFields' => ['reminder_type', 'remind_at'],
                'editFields' => [],
            ],
        ],
    ],
];
